export const leadersData = [
    // {
    //   id: 1,
    //   name: "Shiblu Ahmad",
    //   title: "Chief Executive Officer",
    //   designation: {
    //     name: 'Principal & Mentor',
    //     titles: ['Software Test Automation Engineer', 'Vehicle Validation Engineer', 'Agile Product Owner']
    //   },
    //   // shortDescription:
    //   //   "If you are a recent graduate or job seeker, now is the moment to jumpstart your career, and we will assist you in securing your ideal job.",
    //   picture: "/leadership/shiblu_bg.png",
    //   // description:
    //   //   "Software Quality Assurance Engineer is the role of a Software Development team, and the responsibilities of a Software Quality Assurance Engineer are to understand the project, requirements of the project, to analyze the requirements, and do testing through the lifecycle of the project. In this life cycle, the quality engineer works in an Agile Scrum environment and completes the functional and non-functional testing which are precise to the business requirements. So it can be Manual Testing and Automation Testing, so here’s why you should choose us:",
    //   // joinDate: "20-11-2021",
    //   workingExperience: [
    //     "Design the e2e transformation course to align with current job market demand",
    //     "Prepare webinar contents",
    //     "Design the e2e course modules",
    //     "Delivery speech on the webinar",
    //     "Design course chapter for the e2e course",
    //     "Design classes for each chapter",
    //     "Lead workshop, classes, and provide group and 1: 1 mentoring",
    //     "Meet 1: 1 for students issue to resolve",
    //     "Meet 1: 1 for the career planning and job search",
    //     "Design and develop workshop contents and lab",
    //     "Provide core training on the SDLC",
    //     "Provide the Agile scrum walkthrough on the agilealm",
    //     "Provide core training on the Java",
    //     "Provide core",
    //     "Provide mentoring to mentor assistance",
    //     "Update and enhance course modules",
    //     "Review course plans and provide feedback",
    //     "Provide hands- on project agile scrum teaching to follow agilealm.cloud",
    //     "Provide hands - on sprint creation to implementation ",
    //     "Coach students while they are learning on agile scrum",
    //     "Coach Software Quality assurance training to use a series of quality practice software and tools."
    //   ],
    // },
    {
        id: 2,
        name: 'Pranto Mazumder',
        title: 'Managing Director',
        designation: {
            name: 'Test Lead',
            titles: [
                'Agile Product Owner',
                'Software Test Automation Engineer',
            ],
        },
        // shortDescription:
        //   "If you are a recent graduate or job seeker, now is the moment to jumpstart your career, and we will assist you in securing your ideal job.",
        picture: '/leadership/pranto_bg.png',
        // description:
        //   "Software Quality Assurance Engineer is the role of a Software Development team, and the responsibilities of a Software Quality Assurance Engineer are to understand the project, requirements of the project, to analyze the requirements, and do testing through the lifecycle of the project. In this life cycle, the quality engineer works in an Agile Scrum environment and completes the functional and non-functional testing which are precise to the business requirements. So it can be Manual Testing and Automation Testing, so here’s why you should choose us:",
        // joinDate: "20-11-2021",
        workingExperience: [
            'Design the e2e course modules',
            'Design course chapter for the e2e course',
            'Design classes for each chapter',
            'Lead workshop, classes and provide group and 1:1 mentoring',
            'Prepare job market profile and make dynamic contents',
            'Provide interview prepreation guideline',
            'Resume review and provide feedback',
            'Provide mock interview assistance',
            'Review mock interview recorded videos',
            'Review workshop contents and course materials',
            'Develop class labs, data, and enhance class contents',
            'Design and develop workshop contents and lab',
            'Provide core training on the SDLC',
            'Provide the Agile scrum walkthrough on the agilealm',
            'Provide core training on the Java',
            'Provide mentoring to mentor assistance',
            'Update and enhance course modules ',
            'Review course plans and provide feedback',
        ],
    },
    {
        id: 3,
        name: 'Shahed Mehbub',
        title: 'Lead CloudOps',
        designation: {
            name: 'DevOps Engineer',
            titles: ['CloudOps Engineer', 'Python Software Engineer'],
        },
        // shortDescription:
        //   "If you are a recent graduate or job seeker, now is the moment to jumpstart your career, and we will assist you in securing your ideal job.",
        picture: '/leadership/shahed_bg.png',
        // description:
        //   "Software Quality Assurance Engineer is the role of a Software Development team, and the responsibilities of a Software Quality Assurance Engineer are to understand the project, requirements of the project, to analyze the requirements, and do testing through the lifecycle of the project. In this life cycle, the quality engineer works in an Agile Scrum environment and completes the functional and non-functional testing which are precise to the business requirements. So it can be Manual Testing and Automation Testing, so here’s why you should choose us:",
        // joinDate: "20-11-2021",
        workingExperience: [
            'Design the e2e course modules',
            'Design course chapter for the e2e course',
            'Design classes for each chapter',
            'Lead workshop, classes, and provide group and 1:1 mentoring',
            'Prepare job market profile and make dynamic contents',
            'Provide interview prepreation guideline',
            'Resume review and provide feedback',
            'Provide mock interview assistance',
            'Review mock interview recorded videos',
            'Review workshop contents and course materials',
            'Develop class labs, data, and enhance class contents',
            'Design and develop workshop contents and lab',
            'Provide core training on AWS cloud',
            'Provide K8S e2e deployment, design lab, and provide hands-on training',
            'Provide core training on the python ',
            'Provide core deployment training on manual application deployment',
            'Provide mentoring to mentor assistance',
            'Update and enhance course modules ',
            'Provide terraform implementation and prepare labs',
            'Provide ansible training and implementation ',
            'Prepare labs on Jenkins CICD',
            'Prepare labs on the gitlab CICD',
            'Prepare and implement K8S implementation with CICD',
            'Provide E2E training on the core AWS cloudops engineer',
        ],
    },
    {
        id: 4,
        name: 'Ahsanuzzaman',
        title: 'Lead Engineer',
        designation: {
            name: 'Software Architect',
            titles: [
                'Java Enterprise Application Software Engineer',
                'Python Software Engineer',
            ],
        },
        // shortDescription:
        //   "If you are a recent graduate or job seeker, now is the moment to jumpstart your career, and we will assist you in securing your ideal job.",
        picture: '/leadership/ahsan.png',
        // description:
        //   "Software Quality Assurance Engineer is the role of a Software Development team, and the responsibilities of a Software Quality Assurance Engineer are to understand the project, requirements of the project, to analyze the requirements, and do testing through the lifecycle of the project. In this life cycle, the quality engineer works in an Agile Scrum environment and completes the functional and non-functional testing which are precise to the business requirements. So it can be Manual Testing and Automation Testing, so here’s why you should choose us:",
        // joinDate: "20-11-2021",
        workingExperience: [
            'Design the e2e course modules',
            'Design course chapter for the e2e course',
            'Design classes for each chapter',
            'Lead workshop, classes, and provide group and 1:1 mentoring',
            'Prepare job market profile and make dynamic contents',
            'Provide interview prepreation guideline',
            'Resume review and provide feedback',
            'Provide mock interview assistance',
            'Review mock interview recorded videos',
            'Review workshop contents and course materials',
            'Develop class labs, data, and enhance class contents',
            'Design and develop workshop contents and lab',
            'Provide core training on the Java ',
            'Provide mentoring to mentor assistance',
            'Update and enhance course modules ',
            'Review course plans and provide feedback',
            'Contribute to all stages of software development lifecycle',
            'Design, implement and maintain Java-based applications that can be high-volume and low-latency',
            'Analyze user requirements to define business objectives',
            'Envisioning system features and functionality',
            'Define application objectives and functionality',
            'Ensure application designs conform with business goals',
            'Develop and test software',
            'Identify and resolve any technical issues arising',
            'Create detailed design documentation',
            'Propose changes to current Java infrastructure',
            'Develop technical designs for application development',
            'Develop multimedia applications',
            'Write well designed, testable code',
            'Conducting software analysis, programming, testing, and debugging',
            'Manage Java, and Java EE application development',
            'Develop documentation to help users',
            'Transform requirements into stipulations.',
            'Prepare and produce releases of software components.',
            'Support continuous improvement, investigating alternatives and technologies, and presenting for architectural review',
        ],
    },

    {
        id: 5,
        name: 'Md. Ashraful Islam Shimul',
        title: 'Lead Software Engineer',
        designation: {
            name: 'Lead Software Engineer',
            titles: [
                'Lead Software Engineer Backend (NodeJS)',
                'Knowledge Transfer Engineer',
            ],
        },
        // shortDescription:
        //   "If you are a recent graduate or job seeker, now is the moment to jumpstart your career, and we will assist you in securing your ideal job.",
        picture: '/leadership/shimul_bg.png',
        // description:
        //   "Software Quality Assurance Engineer is the role of a Software Development team, and the responsibilities of a Software Quality Assurance Engineer are to understand the project, requirements of the project, to analyze the requirements, and do testing through the lifecycle of the project. In this life cycle, the quality engineer works in an Agile Scrum environment and completes the functional and non-functional testing which are precise to the business requirements. So it can be Manual Testing and Automation Testing, so here’s why you should choose us:",
        // joinDate: "20-11-2021",
        workingExperience: [
            'Working with clients to develop the overall look and design of a website',
            'Writing website code with programming languages such as HTML, C++, and Java',
            'Producing, maintaining, and modifying websites and user interfaces',
            'Incorporating applications, graphics, audio and video clips into client websites',
            'Creating tools that enhance the user’s website experience',
            'Ensuring websites are accessible across many platforms, including laptops and smartphones',
            'Routinely testing websites for ease of use, speed and other quality factors',
            'Fixing any website issues or bugs that arise',
            'Develop Ts4U.us (end2end platform)',
            'Develop ts4u’s mobile app',
            'Develop Ts4u’s desktop app',
            'Develop agilealm.cloud platform',
            'Provide platform design, configuration, and deployment',
            'Prepare CICD and manage day to day deployment ',
            'Delivery day to day assigned work and fix bugs',
            'Enhance existing features and fix bugs as founds',
            'Develop POC for microservices to break down existing platform and develop to follow micro service architecture',
            'Enhance and bug fixes of mobile application',
            'Provide students technical support also knowledge transfer while they are learning',
            'Enhance and bug fixes on desktop application also explain a bug while students are learning',
            'Develp new features and enhance existing features of each platform of TS4U, also share knowledge with students as requested by the mentor ',
        ],
    },

    {
        id: 6,
        name: 'Osman Goni',
        title: 'HR & Payroll',
        designation: {
            name: 'Head of HR',
            titles: [],
        },
        // shortDescription:
        //   "If you are a recent graduate or job seeker, now is the moment to jumpstart your career, and we will assist you in securing your ideal job.",
        picture: '/leadership/osman_goni.png',
        // description:
        //   "Software Quality Assurance Engineer is the role of a Software Development team, and the responsibilities of a Software Quality Assurance Engineer are to understand the project, requirements of the project, to analyze the requirements, and do testing through the lifecycle of the project. In this life cycle, the quality engineer works in an Agile Scrum environment and completes the functional and non-functional testing which are precise to the business requirements. So it can be Manual Testing and Automation Testing, so here’s why you should choose us:",
        // joinDate: "20-11-2021",
        workingExperience: [
            'Engage with new customers to determine their individual or family needs, and guide them through the entire enrollment process',
            'Educate customers about their new benefits and answer any questions they may have',
            'Escalate problems or concerns to the appropriate supervisor, and check in with customers to ensure their questions have been fully answered',
            'Track customer data in our computerized system, observing all patient confidentiality laws and guidelines',
            'Update student information',
            'Provide student enrollment guideline',
            'Provide student onboarding',
            'Review student day to day 1:1 chat, day to day activities, accept meeting, provide technical support',
            'Assist with software installation, configuration, workshop update, workshop upload',
            'Prepare workshop contents, slide, documents, and provide information as needed',
            'Prepare exiting and new students progress ',
            'Send monthly progress report to students for their quarterly progress',
            'Respond to email and chat for students issues related to their course',
            'Provide access permission to a course after enrollment complete ',
            'Prepare chat group, and add students to require chat groups when a new session starts',
            'Prepare students list to identify existing and new students joined for a new session',
            'Respond to social media as part of the back up social media expert',
        ],
    },
    {
        id: 7,
        name: 'Abdullah Al Mamun',
        title: 'Lead Program Analyst',
        designation: {
            name: 'Head of Marketing',
            title: [],
        },
        // shortDescription:
        //   "If you are a recent graduate or job seeker, now is the moment to jumpstart your career, and we will assist you in securing your ideal job.",
        picture: '/leadership/mamun_bg.png',
        // description:
        //   "Software Quality Assurance Engineer is the role of a Software Development team, and the responsibilities of a Software Quality Assurance Engineer are to understand the project, requirements of the project, to analyze the requirements, and do testing through the lifecycle of the project. In this life cycle, the quality engineer works in an Agile Scrum environment and completes the functional and non-functional testing which are precise to the business requirements. So it can be Manual Testing and Automation Testing, so here’s why you should choose us:",
        // joinDate: "20-11-2021",
        workingExperience: [
            'Engage with new customers to determine their individual or family needs, and guide them through the entire enrollment process',
            'Educate customers about their new benefits and answer any questions they may have',
            'Escalate problems or concerns to the appropriate supervisor, and check in with customers to ensure their questions have been fully answered',
            'Track customer data in our computerized system, observing all patient confidentiality laws and guidelines',
            'Update student information',
            'Provide student enrollment guideline',
            'Provide student onboarding',
            'Review student day to day 1:1 chat, day to day activities, accept meeting, provide technical support',
            'Assist with software installation, configuration, workshop update, workshop upload',
            'Prepare workshop contents, slide, documents, and provide information as neede',
            'Lead workshop for the Linux and Database query',
            'Lead workshop for the Linux and Database query',
            'Provide hands-on slides to students',
            'Prepare cloudops contents and delivery in the workshop',
            'Cooridante with lead mentor to review workshop contents',
            'Prepare webinar contents and review with lead mentor',
            'Enhance existing lab documents ',
            'Prepare new hands on labs on AWS',
            'Prepare slides for the various cloudops chapter and modules',
            'Prepare mock interview contents and questions',
            'Prepare interview contents and provide job readiness assistance',
            'Take mock interview after a student complete the course',
            'Asist with job apply, interview questions and answers, and assist with interview preparation',
            'OnProvide offer letter negotiation tipsboard',
            'Prepare each course content, update, upload workshop videos, enhance existing contents and provide technical support ',
        ],
    },

    {
        id: 8,
        name: 'Eusha Bin Farhad',
        title: 'QA Support Member',
        designation: {
            name: 'Quality Analyst',
            titles: [],
        },
        // shortDescription:
        //   "If you are a recent graduate or job seeker, now is the moment to jumpstart your career, and we will assist you in securing your ideal job.",
        picture: '/leadership/eusha_bg.png',
        // description:
        //   "Software Quality Assurance Engineer is the role of a Software Development team, and the responsibilities of a Software Quality Assurance Engineer are to understand the project, requirements of the project, to analyze the requirements, and do testing through the lifecycle of the project. In this life cycle, the quality engineer works in an Agile Scrum environment and completes the functional and non-functional testing which are precise to the business requirements. So it can be Manual Testing and Automation Testing, so here’s why you should choose us:",
        // joinDate: "20-11-2021",
        workingExperience: [
            'Engage with new customers to determine their individual or family needs, and guide them through the entire enrollment process',
            'Educate customers about their new benefits and answer any questions they may have',
            'Escalate problems or concerns to the appropriate supervisor, and check in with customers to ensure their questions have been fully answered',
            'Track customer data in our computerized system, observing all patient confidentiality laws and guidelines',
            'Update student information',
            'Provide student enrollment guideline',
            'Provide student onboarding',
            'Review student day to day 1:1 chat, day to day activities, accept meeting, provide technical support',
            'Assist with software installation, configuration, workshop update, workshop upload',
            'Prepare workshop contents, slide, documents, and provide information as neede',
            'Lead workshop for the Linux and Database query',
            'Provide hands-on slides to students',
            'Prepare cloudops contents and delivery in the workshop',
            'Cooridante with lead mentor to review workshop contents',
            'Prepare webinar contents and review with lead mentor',
            'Enhance existing lab documents ',
            'Prepare new hands on labs on AWS',
            'Prepare slides for the various cloudops chapter and modules',
            'Prepare mock interview contents and questions',
            'Prepare interview contents and provide job readiness assistance',
            'Take mock interview after a student complete the course',
            'Asist with job apply, interview questions and answers, and assist with interview preparation',
            'Provide offer letter negotiation tips',
        ],
    },

    // {
    //   name: "Enamul Hoque",
    //   title: "CloudOps Support Member",
    //   // shortDescription:
    //   //   "If you are a recent graduate or job seeker, now is the moment to jumpstart your career, and we will assist you in securing your ideal job.",
    //   picture: "/leadership/enamul_bg.png",
    //   // description:
    //   //   "Software Quality Assurance Engineer is the role of a Software Development team, and the responsibilities of a Software Quality Assurance Engineer are to understand the project, requirements of the project, to analyze the requirements, and do testing through the lifecycle of the project. In this life cycle, the quality engineer works in an Agile Scrum environment and completes the functional and non-functional testing which are precise to the business requirements. So it can be Manual Testing and Automation Testing, so here’s why you should choose us:",
    //   // joinDate: "20-11-2021",
    //   workingExperience: [
    //     "Join DS.",
    //     "Plan to Work.",
    //     "Share the progress of previously imposed.",
    //     "Accept a new assignment and fix the deadline.",
    //     "Support to Trainees if required.",
    //     "Share the last update before leaving.",
    //     "Support to Trainee.",
    //     "Technical Document prepare.",
    //     "Workshop Document prepare or enhance.",
    //     "Workshop agenda prepare or enhance.",
    //     "Assist other teammates.",
    //     "Assist to DevOps Mentor.",
    //     "Learned DevOps culture.",
    //     "Learned Tutorial Document prepare process.",
    //     "Learned a huge new technology.",
    //     "Learned  new methods of the learning process.",
    //   ],
    // },

    // {
    //   name: "Murshalin Ridoy",
    //   title: "QA Support Member",
    //   // shortDescription:
    //   //   "If you are a recent graduate or job seeker, now is the moment to jumpstart your career, and we will assist you in securing your ideal job.",
    //   picture: "/leadership/Murshalin Ridoy.png",
    //   // description:
    //   //   "Software Quality Assurance Engineer is the role of a Software Development team, and the responsibilities of a Software Quality Assurance Engineer are to understand the project, requirements of the project, to analyze the requirements, and do testing through the lifecycle of the project. In this life cycle, the quality engineer works in an Agile Scrum environment and completes the functional and non-functional testing which are precise to the business requirements. So it can be Manual Testing and Automation Testing, so here’s why you should choose us:",
    //   // joinDate: "20-11-2021",
    //   workingExperience: [
    //     "Daily standup and ending meeting.",
    //     "Develop web applications automation framework.",
    //     "Updated daily scrum board and activities.",
    //     "Helping job holder members.",
    //     "Writing manual test cases.",
    //     "Web/Mobile Application Automation Tester.",
    //     "Automatically/Manually Test API.",
    //     "Give Support to the SQE members.",
    //     "Onboard the new Members.",
    //     "Develop the Web Automation Frameworks.",
    //   ],
    // },

    {
        id: 9,
        name: 'Rafiur Rahman Protik',
        title: 'Front-End Developer',
        designation: {
            name: 'Software Engineer',
            titles: ['Front-End Developer', 'JavaScripts (NodeJS)'],
        },
        // shortDescription:
        //   "If you are a recent graduate or job seeker, now is the moment to jumpstart your career, and we will assist you in securing your ideal job.",
        picture: '/leadership/protik_new.png',
        // description:
        //   "Software Quality Assurance Engineer is the role of a Software Development team, and the responsibilities of a Software Quality Assurance Engineer are to understand the project, requirements of the project, to analyze the requirements, and do testing through the lifecycle of the project. In this life cycle, the quality engineer works in an Agile Scrum environment and completes the functional and non-functional testing which are precise to the business requirements. So it can be Manual Testing and Automation Testing, so here’s why you should choose us:",
        // joinDate: "20-11-2021",
        workingExperience: [
            'Proficiency in website programming languages such as HTML, C#, CSS, Python, and JavaScript',
            'Understanding of key website design principles and SEO optimization',
            'Ability to use client input to create functional, creative and user-friendly webpages',
            'Ability to test and debug websites',
            'Analytical and detail-oriented',
            'Excellent verbal and written communication skills',
            'Advanced problem-solving skills',
            'Observant and able to remain focused on tasks for long periods of time',
            'Join daily stand up',
            'Review students project',
            'Provide technical assistance to software engineering students',
            'Update and enhance on the front end application (web)',
            'Update various companies application front end (web)',
            'Review, and delivery day to day user stories',
            'Bug fix on existing and newly found issues on the web',
            'Join sprint planning meeting',
            'Review students assignment and task',
            'Assist students with day to day work review',
            'Provide technical support as needed ',
            'Respond to meeting for 1:1 assignment and task review',
            'Continue improve ts4u.us website and enhance new contents that is SEO friendly',
            'Provide offer letter negotiation tips',
        ],
    },
    ,
    {
        id: 10,
        name: 'Md Ashiq Mahmood',
        title: 'AWS CloudOps Mentor Assistance',
        designation: {
            name: 'DevOps Engineer',
            title: [],
        },
        // shortDescription:
        //   "If you are a recent graduate or job seeker, now is the moment to jumpstart your career, and we will assist you in securing your ideal job.",
        picture: '/leadership/ashiq.png',
        // description:
        //   "Software Quality Assurance Engineer is the role of a Software Development team, and the responsibilities of a Software Quality Assurance Engineer are to understand the project, requirements of the project, to analyze the requirements, and do testing through the lifecycle of the project. In this life cycle, the quality engineer works in an Agile Scrum environment and completes the functional and non-functional testing which are precise to the business requirements. So it can be Manual Testing and Automation Testing, so here’s why you should choose us:",
        // joinDate: "20-11-2021",
        workingExperience: [
            'Engage with new customers to determine their individual or family needs, and guide them through the entire enrollment process',
            'Educate customers about their new benefits and answer any questions they may have',
            'Escalate problems or concerns to the appropriate supervisor, and check in with customers to ensure their questions have been fully answered',
            'Track customer data in our computerized system, observing all patient confidentiality laws and guidelines',
            'Update student information',
            'Provide student enrollment guideline',
            'Provide student onboarding',
            'Review student day to day 1:1 chat, day to day activities, accept meeting, provide technical support',
            'Assist with software installation, configuration, workshop update, workshop upload',
            'Prepare workshop contents, slide, documents, and provide information as neede',
            'Lead workshop for the Linux and Database query',
            'Provide hands-on slides to students',
            'Prepare cloudops contents and delivery in the workshop',
            'Cooridante with lead mentor to review workshop contents',
            'Prepare webinar contents and review with lead mentor',
            'Prepare technical questions based on the workshop weekly basis',
            'Review technical questions and answers',
            'Provide technical support to cloudops students',
            'Provide 1:1 support to cloudops students for a given issue',
            'Provide agilealm walkthrough for a given sprint',
            'Prepare sprint, update sprint, and provide sprint info to each group',
            'Prepare and update sprint retro',
            'Take mock interview after a student complete the course',
            'Asist with job apply, interview questions and answers, and assist with interview preparation',
        ],
    },

    {
        id: 11,
        name: 'Aleisha Ahmad',
        title: 'Human Resources Director',
        designation: {
            name: 'Director of HR',
            title: [],
        },
        // shortDescription:
        //   "If you are a recent graduate or job seeker, now is the moment to jumpstart your career, and we will assist you in securing your ideal job.",
        picture: '/placeholder.jpg',
        // description:
        //   "Software Quality Assurance Engineer is the role of a Software Development team, and the responsibilities of a Software Quality Assurance Engineer are to understand the project, requirements of the project, to analyze the requirements, and do testing through the lifecycle of the project. In this life cycle, the quality engineer works in an Agile Scrum environment and completes the functional and non-functional testing which are precise to the business requirements. So it can be Manual Testing and Automation Testing, so here’s why you should choose us:",
        // joinDate: "20-11-2021",
        workingExperience: [
            'Act as President of the company',
            'Lead various meeting to make a decision for a given plan to move forward',
            'Decision on investing and priortize a plan to implement',
            'Decision making on new ideas and implementation ',
            'Review student enrollment',
            'Review payment for the full amount and the monthlsy',
            'Collect monthly installment',
            'Prepare monthly statement for the payment collection',
            'Prepare monthly statement for the operational cost for the technology',
            'Prepare monthly standment for the operation cost related to the office expense',
            'Comunicate and collaborate with the CPA team to provide necessary information ',
            'Provide background information and assist with offer letter document and complettation',
            'Provide testimonial after course completion',
            'Set up 1:1 meeting with students who are behind the payment',
            'Collaborate with collection and attorney for the debt collection',
            'Plan for the quarterly goal and implementation streagy to accomplish ',
        ],
    },

    {
        id: 12,
        name: 'Nargish Ara Begum',
        title: 'Enrollment Specialist',
        designation: {
            name: 'Marketing Specialist',
            title: [],
        },
        // shortDescription:
        //   "If you are a recent graduate or job seeker, now is the moment to jumpstart your career, and we will assist you in securing your ideal job.",
        picture: '/placeholder.jpg',
        // description:
        //   "Software Quality Assurance Engineer is the role of a Software Development team, and the responsibilities of a Software Quality Assurance Engineer are to understand the project, requirements of the project, to analyze the requirements, and do testing through the lifecycle of the project. In this life cycle, the quality engineer works in an Agile Scrum environment and completes the functional and non-functional testing which are precise to the business requirements. So it can be Manual Testing and Automation Testing, so here’s why you should choose us:",
        // joinDate: "20-11-2021",
        workingExperience: [
            'Engage with new customers to determine their individual or family needs, and guide them through the entire enrollment process',
            'Educate customers about their new benefits and answer any questions they may have',
            'Escalate problems or concerns to the appropriate supervisor, and check in with customers to ensure their questions have been fully answered',
            'Track customer data in our computerized system, observing all patient confidentiality laws and guidelines',
            'Update student information',
            'Provide student enrollment guideline',
            'Provide student onboarding',
            'Review student day to day 1:1 chat, day to day activities, accept meeting, provide technical support',
            'Assist with software installation, configuration, workshop update, workshop upload',
            'Prepare workshop contents, slide, documents, and provide information as needed',
            'Social media post and marketing',
            'Set up social media contents',
            'Set up social media ads and respond to future student questions',
        ],
    },

    {
        id: 13,
        name: 'Mahamudul Haque',
        title: 'Payment and Client Relation Specialist',
        designation: {
            name: 'Account Manager',
            title: [],
        },
        // shortDescription:
        //   "If you are a recent graduate or job seeker, now is the moment to jumpstart your career, and we will assist you in securing your ideal job.",
        picture: '/placeholder.jpg',
        // description:
        //   "Software Quality Assurance Engineer is the role of a Software Development team, and the responsibilities of a Software Quality Assurance Engineer are to understand the project, requirements of the project, to analyze the requirements, and do testing through the lifecycle of the project. In this life cycle, the quality engineer works in an Agile Scrum environment and completes the functional and non-functional testing which are precise to the business requirements. So it can be Manual Testing and Automation Testing, so here’s why you should choose us:",
        // joinDate: "20-11-2021",
        workingExperience: [
            'Engage with new customers to determine their individual or family needs, and guide them through the entire enrollment process',
            'Educate customers about their new benefits and answer any questions they may have',
            'Escalate problems or concerns to the appropriate supervisor, and check in with customers to ensure their questions have been fully answered',
            'Track customer data in our computerized system, observing all patient confidentiality laws and guidelines',
            'Update student information',
            'Provide student enrollment guideline',
            'Provide student onboarding',
            'Review student day to day 1:1 chat, day to day activities, accept meeting, provide technical support',
            'Assist with software installation, configuration, workshop update, workshop upload',
            'Prepare workshop contents, slide, documents, and provide information as needed',
            'Prepare monthly statement for the payment collection',
            'Prepare monthly statement for the operational cost for the technology',
            'Prepare monthly standment for the operation cost related to the office expense',
            'Comunicate and collaborate with the CPA team to provide necessary information ',
            'Provide background information and assist with offer letter document and complettation',
            'Provide testimonial after course completion',
            'Set up 1:1 meeting with students who are behind the payment',
            'Collaborate with collection and attorney for the debt collection',
        ],
    },
];
